services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    restart: always
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - infra-net
    expose:
      - "8080"
      - "50000" # Jenkins agent port

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    depends_on:
      - jenkins
    networks:
      - infra-net
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      # - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # - ./ssl:/etc/nginx/ssl # if using TLS/SSL
      - ./nginx/log:/var/log/nginx

# Define external volumes and networks
volumes:
  jenkins_data:
    external: true

networks:
  infra-net:
    external: true